import { Router } from "express"
import { isAuth, mustAuth } from "../middleware/auth"
import { getAutoGeneratedPlaylist, getFollowersProfile, getFollowersProfilePublic, getFollowingsProfile, getIsFollowing, getPlaylistAudios, getPublicPlaylist, getPublicProfile, getPublicUploads, getRecommendByProfile, getUploads, updateFollower } from "../controllers/profile"

const router = Router()
router.post('/update-follower/:profileId', mustAuth, updateFollower)
router.get("/uploads", mustAuth, getUploads);
router.get("/uploads/:profileId", getPublicUploads);
router.get("/info/:profileId", getPublicProfile);
router.get("/playlist/:profileId", getPublicPlaylist);
router.get("/recommended", isAuth, getRecommendByProfile);
router.get("/auto-generated-playlist", mustAuth, getAutoGeneratedPlaylist);
router.get("/followers", mustAuth, getFollowersProfile);
router.get("/followers/:profileId", mustAuth, getFollowersProfilePublic);
router.get("/followings", mustAuth, getFollowingsProfile);
router.get("/playlist-audios/:playlistId", getPlaylistAudios);
router.get("/is-following/:profileId", getIsFollowing);




export default router